apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJjbTFwYm1Ob1lXdHZkanBuYUhCZlMyOVpNR1ZwTkdaRVQweERWVVpWTjJ0RGFteFhTalpGVFUxd1RFRTBNbTVOTnpNeCIKICAgICAgICB9CiAgICB9LAogICAgImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCiAgICAiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQo=
type: kubernetes.io/dockerconfigjson
